window.SCREENS.gameplay=function(UI){
  const s=UI.screen("gameplay");UI.back(s,"home",38,31,41,41,"gameplay/back");
  const mode=UI.el("button","game-top-pill click",{left:"90px",top:"34px",width:"128px",height:"32px"},"gameplay/mode");mode.type="button";mode.dataset.nav="home";mode.textContent="📖  Классика";s.appendChild(mode);
  const eru=UI.el("div","panel round",{position:"absolute",left:"246px",top:"34px",width:"88px",height:"32px",display:"flex",alignItems:"center",justifyContent:"center",gap:"6px"},"gameplay/erudition");UI.sprite(eru,"ui","Crown",8,3,28,25);let e=document.createElement("b");e.textContent="0";eru.appendChild(e);s.appendChild(eru);
  const hi=UI.el("div","panel round",{position:"absolute",left:"389px",top:"27px",width:"44px",height:"47px"},"gameplay/hint");UI.sprite(hi,"ui","Bulb",7,8,30,30);e=UI.el("b","ui",{right:"-5px",top:"-7px",width:"22px",height:"22px",borderRadius:"50%",background:"#168ff3",color:"white",display:"grid",placeItems:"center",fontSize:"11px"});e.textContent="2";hi.appendChild(e);s.appendChild(hi);
  const hearts=UI.group(s,"gameplay/hearts",186,91,103,32,"hearts");hearts.innerHTML="<span class='heart'>♥</span><span class='heart'>♥</span><span class='heart'>♥</span>";UI.image(s,UI.OWL.normal,138,128,160,118,"","gameplay/owl");
  const parchment=UI.group(s,"gameplay/parchment",42,248,393,432);UI.sprite(parchment,"surfaces","Parchment",0,0,393,432,"gameplay/parchment/surface");const info=UI.el("div","game-copy",{left:"54px",top:"12px",width:"285px",height:"49px"},"gameplay/parchment/info");info.innerHTML="Лёгкий · Цитаты и мысли<br>Осталось 35 букв · 6 слов<br><small>Открыто 6 из 41 букв</small>";parchment.appendChild(info);const prog=UI.el("div","ui",{left:"27px",top:"66px",width:"322px",height:"5px",background:"#ddd6b8"},"gameplay/parchment/progress");prog.appendChild(UI.el("div","ui",{left:"0",top:"0",width:"51px",height:"5px",background:"#39aa87"}));parchment.appendChild(prog);
  const cipher=UI.el("div","cipher",{left:"36px",right:"36px",top:"92px",height:"270px"},"gameplay/parchment/cipher");const rows=[[["","И","","","Е"],["","","",""]],[["","","","","","","",""]],[["","С","","","","","",""],["","Л","",""]],[["","В","","","",""],["","Р","","","","",""]]];rows.forEach(function(rd,ri){const row=UI.el("div","cipher-row",{height:(ri===0?58:55)+"px"});rd.forEach(function(wd,wi){const word=UI.el("div","word");wd.forEach(function(ch,ci){const cell=UI.el("div","cell"+(ri===0&&wi===0&&ci===0?" sel":""));cell.textContent=ch;const sm=document.createElement("small");sm.textContent=String((ri*7+wi*4+ci)%19+1);cell.appendChild(sm);word.appendChild(cell)});row.appendChild(word)});cipher.appendChild(row)});parchment.appendChild(cipher);
  const kb=UI.group(s,"gameplay/keyboard",38,709,397,166,"keyboard");["Й","Ц","У","К","Е","Н","Г","Ш","Щ","З","Х","Ъ","Ф","Ы","В","А","П","Р","О","Л","Д","Ж","Э","Ё","Я","Ч","С","М","И","Т","Ь","Б","Ю"].forEach(function(l){const k=document.createElement("button");k.type="button";k.className="key"+(["Е","В","Р","Л","С"].includes(l)?" used":"")+(l==="И"?" disabled":"");k.textContent=l;kb.appendChild(k)});
  return s;
};